---
# This playbook deploys the whole application stack in this site.  

- name: deploy to dmt server
  hosts: main-site
  remote_user: root

  vars_files:
    - vars/prima-dm-site
    - github-credentials.yml

  roles:
    - app
    - server
