---
# Install python2.7 and pip

- name: install python2.7
  yum: name=python27 state=present

- name: install setuptools
  yum: name=python27-setuptools state=present

- name: install iris
  yum: name=python27-iris state=present

- name: install pip
  easy_install: name=pip executable=/usr/bin/easy_install-2.7

- name: install virtualenv
  pip: name=virtualenv executable=/usr/bin/pip2.7
  
- name: install sqlalchemy
  pip: name=sqlalchemy executable=/usr/bin/pip2.7
